import type { Metadata } from "next";
import localFont from "next/font/local";

const geistMono = localFont({
  src:"./fonts/GeistMonoVF.woff",
  variable:"--font-geist-mono",
  weight:"100 900"
});

const geistSans = localFont({
  src:"./fonts/GeistVF.woff",
  preload:true,
  variable:"--font-geist-sans",
  weight:"100 900"
})

export const metadata:Metadata = {
  title:"News App",
  description: "this is app for latest news"
}

export default function RootLayout({children,}:Readonly<{children:React.ReactNode}>){
    return (
      <html>
        <body>
          <div className={`${geistMono.variable} ${geistSans.variable}, antialiased`}>{children}</div>
        </body>
      </html>
    )
}































// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
